services:
  db:
    image: postgres:14-alpine
    container_name: company-review-db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  backend:
    build: ./backend
    restart: unless-stopped 
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app 
      - /app/node_modules 
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=development
      - DB_HOST=db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s 
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend 
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true 
      - API_URL_SERVER=http://backend:5001
      - NEXT_PUBLIC_API_URL_CLIENT=http://localhost:5001
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      backend:
        condition: service_healthy 

volumes:
  postgres_data: